# Generated by Django 3.1.3 on 2020-11-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=25)),
                ('product', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
            ],
        ),
    ]
