# Generated by Django 3.1.3 on 2020-11-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore_home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prod_Cat',
        ),
    ]
