# Generated by Django 3.1.3 on 2020-11-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore_home', '0005_order_payment_shipper_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CR', 'Credit Card'), ('Dr', 'Debit Card'), ('COD', 'Cash On Delivery')], max_length=3),
        ),
    ]
