# Generated by Django 3.1.3 on 2020-11-23 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore_home', '0008_auto_20201121_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('item_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mystore_home.product_cat')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystore_home.supplier')),
            ],
        ),
    ]
