# Generated by Django 3.1.3 on 2020-11-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore_home', '0010_auto_20201123_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mystore_home.item_cat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
