# Generated by Django 3.1.3 on 2020-11-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore_home', '0011_auto_20201126_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
