# Generated by Django 3.1.3 on 2020-11-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore_home', '0013_auto_20201128_0948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Details',
            new_name='Product_Detail',
        ),
    ]
