# Generated by Django 3.1.3 on 2020-11-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore_home', '0017_auto_20201128_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gender_Cat',
            new_name='Collection',
        ),
        migrations.RenameField(
            model_name='product_cat',
            old_name='gender',
            new_name='collection',
        ),
    ]
