# Generated by Django 3.1.3 on 2020-11-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore_users', '0003_auto_20201120_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Must Enter email', max_length=254, verbose_name='email address'),
        ),
    ]
